/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TugasAkhir;

import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salome
 */
public class AnggotaPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnggotaPanel
     */
    public AnggotaPanel(boolean admin) {
        initComponents();
        deleteButton.setVisible(false);
        editButton.setVisible(false);
        if(admin==false) {
            entriPanel.setVisible(false);
        }
        loadTableData();
        clearForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        anggotaTable = new javax.swing.JTable();
        entriPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        memberComboBox = new javax.swing.JComboBox<>();
        roleComboBox = new javax.swing.JComboBox<>();
        angkatanSpinner = new javax.swing.JSpinner();
        nimTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jkComboBox = new javax.swing.JComboBox<>();
        eaButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1110, 680));
        setPreferredSize(new java.awt.Dimension(1110, 660));
        setLayout(new java.awt.GridLayout(1, 0));

        anggotaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Angkatan", "NIM", "Nama", "Role", "Keanggotaan"
            }
        ));
        anggotaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anggotaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(anggotaTable);

        add(jScrollPane1);

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("Angkatan");

        jLabel4.setText("Role");

        jLabel5.setText("Keanggotaan");

        memberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ketua", "Wakil Ketua", "Sekretaris", "Bendahara", "PSDM", "HPD", "Perlengkapan", "Anggota" }));

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vokal", "Gitar", "Piano", "Bass", "Drum" }));

        angkatanSpinner.setModel(new javax.swing.SpinnerNumberModel(62, 62, 63, 1));
        angkatanSpinner.setName(""); // NOI18N

        saveButton.setText("Simpan");
        saveButton.setMaximumSize(new java.awt.Dimension(172, 24));
        saveButton.setMinimumSize(new java.awt.Dimension(172, 24));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Gender");

        jkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        eaButton.setText("Ekspor Tabel");
        eaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entriPanelLayout = new javax.swing.GroupLayout(entriPanel);
        entriPanel.setLayout(entriPanelLayout);
        entriPanelLayout.setHorizontalGroup(
            entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entriPanelLayout.createSequentialGroup()
                        .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(entriPanelLayout.createSequentialGroup()
                                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(44, 44, 44)
                                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameTextField)
                                        .addComponent(angkatanSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(memberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(entriPanelLayout.createSequentialGroup()
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(entriPanelLayout.createSequentialGroup()
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addGroup(entriPanelLayout.createSequentialGroup()
                        .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(eaButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        entriPanelLayout.setVerticalGroup(
            entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(angkatanSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(memberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(entriPanelLayout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(entriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButton)
                            .addComponent(deleteButton)))
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(eaButton)
                .addContainerGap())
        );

        add(entriPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            Anggota aggt = new Anggota();
            aggt.setNama(nameTextField.getText());
            aggt.setNim(nimTextField.getText());
            Integer akt = (Integer) angkatanSpinner.getValue();
            aggt.setAngkatan(akt);
            if(jkComboBox.getSelectedIndex() == 0) {
                aggt.setGender("L");
            } else {
                aggt.setGender("P");
            }
            aggt.setRole(roleComboBox.getSelectedItem().toString());
            aggt.setKeanggotaan(memberComboBox.getSelectedItem().toString());
            
            try {
                Database.getInstance().insertAnggota(aggt);
                JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
                loadTableData();
                clearForm();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Gagal Menyimpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harap isi form dengan benar");
        }
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        loadTableData();
        clearForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void anggotaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaTableMouseClicked
        // TODO add your handling code here:
        clearForm();
        editButton.setVisible(true);
        deleteButton.setVisible(true);
        saveButton.setVisible(false);
        PreparedStatement ps;
        ResultSet rs;
        int row = anggotaTable.getSelectedRow();
        String sql = "SELECT * FROM member WHERE NIM = ?";
        String NIM = anggotaTable.getValueAt(row, 1).toString();
        if(row!=-1){
            try {
                ps = Config.getConnection().prepareStatement(sql);
                ps.setString(1, NIM);
                rs = ps.executeQuery();
                if(rs.next()){
                    Anggota aggt = new Anggota();
                    aggt.setNim(rs.getString("nim"));
                    aggt.setNama(rs.getString("nama"));
                    aggt.setGender(rs.getString("gender"));
                    aggt.setAngkatan(rs.getInt("angkatan"));
                    aggt.setRole(rs.getString("role"));
                    aggt.setKeanggotaan(rs.getString("keanggotaan"));
                    
                    nimTextField.setText(aggt.getNim());
                    nameTextField.setText(aggt.getNama());
                    if("L".equals(aggt.getGender())){
                        jkComboBox.setSelectedIndex(0);
                    }else{
                        jkComboBox.setSelectedIndex(1);
                    }
                    angkatanSpinner.setValue(aggt.getAngkatan());
                    switch(aggt.getRole()){
                        case "Vokal" -> roleComboBox.setSelectedIndex(0);
                        case "Gitar" -> roleComboBox.setSelectedIndex(1);
                        case "Piano" -> roleComboBox.setSelectedIndex(2);
                        case "Bass" -> roleComboBox.setSelectedIndex(3);
                        case "Drum" -> roleComboBox.setSelectedIndex(4);
                        default -> roleComboBox.setSelectedIndex(0);
                    }
                    switch(aggt.getKeanggotaan()){
                        case "Ketua" -> memberComboBox.setSelectedIndex(0);
                        case "Wakil Ketua" -> memberComboBox.setSelectedIndex(1);
                        case "Sekretaris" -> memberComboBox.setSelectedIndex(2);
                        case "Bendahara" -> memberComboBox.setSelectedIndex(3);
                        case "PSDM" -> memberComboBox.setSelectedIndex(4);
                        case "HPD" -> memberComboBox.setSelectedIndex(5);
                        case "Perlengkapan" -> memberComboBox.setSelectedIndex(6);
                        case "Anggota" -> memberComboBox.setSelectedIndex(7);
                        default -> memberComboBox.setSelectedIndex(0);
                    }
                }
                
            } catch (Exception ex) {
                System.err.println(ex);
            }
        }
    }//GEN-LAST:event_anggotaTableMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = anggotaTable.getSelectedRow();
        if (row != -1) {
            String NIM = anggotaTable.getValueAt(row, 1).toString();
            try {
                Database.getInstance().deleteAnggota(NIM);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTableData();
                clearForm();
            } catch (SQLException ex) {
//                System.err.println(ex);
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        
        int row = anggotaTable.getSelectedRow();
        String NIM = anggotaTable.getValueAt(row, 1).toString();
        Anggota aggt = new Anggota();
        aggt.setNim(nimTextField.getText());
        aggt.setNama(nameTextField.getText());
        Integer angkatan = (Integer) angkatanSpinner.getValue();
        aggt.setAngkatan(angkatan);
        if(jkComboBox.getSelectedIndex() == 0) {
            aggt.setGender("L");
        } else{
            aggt.setGender("P");
        }
        aggt.setRole(roleComboBox.getSelectedItem().toString());
        aggt.setKeanggotaan(memberComboBox.getSelectedItem().toString());
        try {
            Database.getInstance().editAnggota(aggt,NIM);
            loadTableData();
            clearForm();
            JOptionPane.showMessageDialog(this, "Sukses Mengubah Data", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal mengubah data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void eaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaButtonActionPerformed
        // TODO add your handling code here:
        Export exp = new Export();
        try {
            exp.exportAnggota("anggota_XBAR.csv");
            JOptionPane.showMessageDialog(this, "Sukses mengekspor file");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengekspor file");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengekspor file");
        }
    }//GEN-LAST:event_eaButtonActionPerformed
    
    private void loadTableData(){
        DefaultTableModel dtm = (DefaultTableModel)
        anggotaTable.getModel();
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        saveButton.setVisible(true);
        deleteButton.setVisible(false);
        editButton.setVisible(false);
        try {
        //isi tabel
            for(Anggota aggt: Database.getInstance().getListAnggota()){
                dtm.addRow(new Object[]{aggt.getAngkatan(),aggt.getNim(),aggt.getNama(),aggt.getRole(),aggt.getKeanggotaan()});
            
        }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void clearForm() {
        nameTextField.setText("");
        nimTextField.setText("");
        angkatanSpinner.setValue(62);
        jkComboBox.setSelectedIndex(-1);
        roleComboBox.setSelectedIndex(-1);
        memberComboBox.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable anggotaTable;
    private javax.swing.JSpinner angkatanSpinner;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton eaButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel entriPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jkComboBox;
    private javax.swing.JComboBox<String> memberComboBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
