/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasAkhir;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author salome
 */
public class MainFrame extends javax.swing.JFrame {
    private boolean admin;
    /**
     * Creates new form MainFrame
     */
    
    public MainFrame(boolean admin) {
        this.admin=admin;
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        this.dashboardButtonActionPerformed();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeBar = new javax.swing.JLabel();
        minBar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        anggotaButton = new javax.swing.JButton();
        inventarisButton = new javax.swing.JButton();
        bandButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contentScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("X-BAR Application");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 45));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(null);

        closeBar.setFont(new java.awt.Font("Waree", 1, 26)); // NOI18N
        closeBar.setForeground(new java.awt.Color(255, 255, 255));
        closeBar.setText("X");
        closeBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBarMouseClicked(evt);
            }
        });
        jPanel1.add(closeBar);
        closeBar.setBounds(1254, 0, 20, 36);

        minBar.setFont(new java.awt.Font("Waree", 1, 26)); // NOI18N
        minBar.setForeground(new java.awt.Color(255, 255, 255));
        minBar.setText("-");
        minBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minBarMouseClicked(evt);
            }
        });
        jPanel1.add(minBar);
        minBar.setBounds(1228, 0, 20, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 0, 32, 45);

        jLabel2.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X-BAR STIS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(44, 5, 114, 33);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 45);

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));

        dashboardButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardButton.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(0, 0, 0));
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseExited(evt);
            }
        });
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        anggotaButton.setBackground(new java.awt.Color(255, 255, 255));
        anggotaButton.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        anggotaButton.setForeground(new java.awt.Color(0, 0, 0));
        anggotaButton.setText("Anggota");
        anggotaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        anggotaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anggotaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                anggotaButtonMouseExited(evt);
            }
        });
        anggotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggotaButtonActionPerformed(evt);
            }
        });

        inventarisButton.setBackground(new java.awt.Color(255, 255, 255));
        inventarisButton.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        inventarisButton.setForeground(new java.awt.Color(0, 0, 0));
        inventarisButton.setText("Inventaris");
        inventarisButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inventarisButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventarisButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventarisButtonMouseExited(evt);
            }
        });
        inventarisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarisButtonActionPerformed(evt);
            }
        });

        bandButton.setBackground(new java.awt.Color(255, 255, 255));
        bandButton.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        bandButton.setForeground(new java.awt.Color(0, 0, 0));
        bandButton.setText("Band Generator");
        bandButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bandButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bandButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bandButtonMouseExited(evt);
            }
        });
        bandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 0, 0));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Uroob", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Yusril Dicky Khoridwan");

        jLabel4.setFont(new java.awt.Font("Uroob", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("222011270");

        jLabel5.setFont(new java.awt.Font("Uroob", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("2KS4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(anggotaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventarisButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(bandButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anggotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventarisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel5))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 170, 680);

        contentScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        contentScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        getContentPane().add(contentScrollPane);
        contentScrollPane.setBounds(170, 40, 1110, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBarMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_minBarMouseClicked

    private void closeBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBarMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x,y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void dashboardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseEntered
        // TODO add your handling code here:
        if(this.dashboardButton.getBackground()!=Color.black){
            this.dashboardButton.setBackground(Color.green);
        }
    }//GEN-LAST:event_dashboardButtonMouseEntered

    private void dashboardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseExited
        // TODO add your handling code here:
        if(this.dashboardButton.getBackground()!=Color.black){
            this.dashboardButton.setBackground(Color.white);
        }
    }//GEN-LAST:event_dashboardButtonMouseExited

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked
        // TODO add your handling code here:
        clearButton();
        this.dashboardButton.setBackground(Color.black);
        this.dashboardButton.setForeground(Color.white);
        contentScrollPane.setViewportView(new DashboardPanel());
    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        clearButton();
        this.dashboardButton.setBackground(Color.black);
        this.dashboardButton.setForeground(Color.white);
        contentScrollPane.setViewportView(new DashboardPanel());
    }//GEN-LAST:event_dashboardButtonActionPerformed
    private void dashboardButtonActionPerformed() {                                                
        // TODO add your handling code here:
        clearButton();
        this.dashboardButton.setBackground(Color.black);
        this.dashboardButton.setForeground(Color.white);
        contentScrollPane.setViewportView(new DashboardPanel());
    }     
    private void anggotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggotaButtonActionPerformed
        // TODO add your handling code here:
        clearButton();
        this.anggotaButton.setBackground(Color.black);
        this.anggotaButton.setForeground(Color.white);
        contentScrollPane.setViewportView(new AnggotaPanel(admin));
    }//GEN-LAST:event_anggotaButtonActionPerformed

    private void inventarisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarisButtonActionPerformed
        // TODO add your handling code here:
        clearButton();
        this.inventarisButton.setBackground(Color.black);
        this.inventarisButton.setForeground(Color.white);
        contentScrollPane.setViewportView(new InventarisPanel(admin));
    }//GEN-LAST:event_inventarisButtonActionPerformed

    private void bandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandButtonActionPerformed
        // TODO add your handling code here:
        clearButton();
        this.bandButton.setBackground(Color.black);
        this.bandButton.setForeground(Color.white);
        contentScrollPane.setViewportView(new BandPanel());
    }//GEN-LAST:event_bandButtonActionPerformed

    private void anggotaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaButtonMouseEntered
        // TODO add your handling code here:
        if(this.anggotaButton.getBackground()!=Color.black){
            this.anggotaButton.setBackground(Color.green);
        }
    }//GEN-LAST:event_anggotaButtonMouseEntered

    private void anggotaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaButtonMouseExited
        // TODO add your handling code here:
        if(this.anggotaButton.getBackground()!=Color.black){
            this.anggotaButton.setBackground(Color.white);
        }
    }//GEN-LAST:event_anggotaButtonMouseExited

    private void inventarisButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarisButtonMouseEntered
        // TODO add your handling code here:
        if(this.inventarisButton.getBackground()!=Color.black){
            this.inventarisButton.setBackground(Color.green);
        }
    }//GEN-LAST:event_inventarisButtonMouseEntered

    private void inventarisButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarisButtonMouseExited
        // TODO add your handling code here:
        if(this.inventarisButton.getBackground()!=Color.black){
            this.inventarisButton.setBackground(Color.white);
        }
    }//GEN-LAST:event_inventarisButtonMouseExited

    private void bandButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bandButtonMouseEntered
        // TODO add your handling code here:
        if(this.bandButton.getBackground()!=Color.black){
            this.bandButton.setBackground(Color.green);
        }
    }//GEN-LAST:event_bandButtonMouseEntered

    private void bandButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bandButtonMouseExited
        // TODO add your handling code here:
        if(this.bandButton.getBackground()!=Color.black){
            this.bandButton.setBackground(Color.white);
        }
    }//GEN-LAST:event_bandButtonMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        this.logoutButton.setBackground(Color.green);
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:
        this.logoutButton.setBackground(Color.white);
    }//GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.logoutButton.setBackground(Color.black);
        this.logoutButton.setForeground(Color.white);
        this.setVisible(false);
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void clearButton(){
        this.anggotaButton.setBackground(Color.white);
        this.anggotaButton.setForeground(Color.black);
        this.dashboardButton.setBackground(Color.white);
        this.dashboardButton.setForeground(Color.black);
        this.inventarisButton.setBackground(Color.white);
        this.inventarisButton.setForeground(Color.black);
        this.bandButton.setBackground(Color.white);
        this.bandButton.setForeground(Color.black);
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anggotaButton;
    private javax.swing.JButton bandButton;
    private javax.swing.JLabel closeBar;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JButton inventarisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel minBar;
    // End of variables declaration//GEN-END:variables
}
